# Generated by Django 4.2 on 2025-03-04 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_actor_movie_actors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name_plural': 'Genuri de film'},
        ),
    ]
